spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/speakwise_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=SpeakWise@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=uploads

app.jwt.secret=ChangeThisToALongRandomSecretKeyForSpeakWiseAppMinimum256BitsLong123
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_ADDRESS
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.enabled=false

app.assemblyai.api-key=c58876f9a094472a9717c776e86e1e90
app.assemblyai.base-url=https://api.assemblyai.com/v2

server.port=8080